# Generated by Django 5.2 on 2025-06-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_personal_chat', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='groups_avatars/default.png', upload_to='groups_avatars/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_group', to='authorization.profile')),
                ('members', models.ManyToManyField(blank=True, to='authorization.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4096)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to='image/messages')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile')),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatgroup')),
            ],
        ),
    ]
