# Generated by Django 5.2 on 2025-06-09 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='avatar_group',
            field=models.ImageField(null=True, upload_to='groups_avatars/'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
