# Generated by Django 5.2 on 2025-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='views',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/messages'),
        ),
    ]
