# Generated by Django 5.2 on 2025-06-12 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='personal_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='views',
            field=models.ManyToManyField(related_name='viewed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
