# Generated by Django 5.2 on 2025-06-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chatmessage_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='avatar',
            field=models.ImageField(default='groups_avatars/default.png', upload_to='images/group_avatars'),
        ),
    ]
