# Generated by Django 5.2 on 2025-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default="{{static 'images/standart_user_image.png'}}", null=True, upload_to='profile_photos/'),
        ),
    ]
