# Generated by Django 5.2 on 2025-06-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_userprofile_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sign',
            field=models.ImageField(blank=True, default='images/standart_sign.png', null=True, upload_to='profile_signs/'),
        ),
    ]
