# Generated by Django 5.2 on 2025-05-16 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
