# Generated by Django 5.2 on 2025-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default='Topic', max_length=255),
            preserve_default=False,
        ),
    ]
