# Generated by Django 5.2 on 2025-06-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
        ('publications', '0002_post_topic'),
    ]

    operations = [
    ]
