# Generated by Django 5.2 on 2025-05-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_user_post_likes_alter_user_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='images',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
