# Generated by Django 5.2 on 2025-05-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_user_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='images',
            field=models.ImageField(default=None, upload_to='media/images/'),
        ),
    ]
