# Generated by Django 5.2 on 2025-05-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_user_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='images',
        ),
    ]
