# Generated by Django 5.2 on 2025-05-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_remove_user_post_images_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
