# Generated by Django 5.2 on 2025-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_remove_user_post_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
