# Generated by Django 5.2 on 2025-06-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userprofile'),
        ('publications', '0015_alter_user_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.userprofile'),
        ),
    ]
